package com.rikkeisoft.backend.model.dto.req.forum;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AccessLevel;
import lombok.Data;
import lombok.experimental.FieldDefaults;

/**
 * Request DTO for creating a new {@link com.rikkeisoft.backend.model.entity.ForumCategory}.
 *
 * <p>The client provides only the {@code name} (and optionally a {@code description}).
 * The {@code slug} is <strong>never accepted from the client</strong>; it is
 * automatically generated by the service layer from the {@code name} using a
 * Vietnamese-aware transliteration and slug-generation algorithm.
 *
 * <p>Example input: {@code name = "Kinh nghiệm phỏng vấn"} →
 * service generates {@code slug = "kinh-nghiem-phong-van"}.
 */
@Data
@FieldDefaults(level = AccessLevel.PRIVATE)
public class ForumCategoryCreateReq {

    /**
     * The human-readable display name of the category.
     * Must not be blank and must be between 2 and 150 characters.
     *
     * <p>This value is used as the source for slug generation.
     * Example: "Kinh nghiệm phỏng vấn".
     */
    @NotBlank(message = "CATEGORY_NAME_REQUIRED")
    @Size(min = 2, max = 150, message = "CATEGORY_NAME_SIZE")
    String name;

    /**
     * Optional brief description of what this category covers.
     * May be {@code null} or empty. Maximum 500 characters.
     */
    @Size(max = 500, message = "CATEGORY_DESCRIPTION_SIZE_CONSTRAINT")
    String description;
}
