spring:
  application:
    name: backend

  config:
    import:
      - optional:file:.env[.properties] # Load .env file if it exists
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: "jdbc:mysql://localhost:${MYSQL_PORT:3306}/headhunt"
    username: root
    password: root
  mail:
    host: smtp.gmail.com
    port: 587
    username: jobsiteheadhunt.forwork@gmail.com
    password: drvb uema xawo sjvj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    from: noreply@headhunt.app
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: PT1H # Cache messages for 1 hour
server:
  port: ${PORT:8080}
  servlet:
    context-path: /headhunt

jwt:
  signerKey: ${JWT_SIGNER_KEY:RikkeisoftHCMcity9998hIrNT3QZjFzSdzZ3YvFWhQyoV4HnOrMbcsrIKMgHMlV}

google:
  client-id: ${GOOGLE_CLIENT_ID:""}
  client-secret: ${GOOGLE_CLIENT_SECRET:""}

linkedin:
  client-id: ${LINKEDIN_CLIENT_ID:""}
  client-secret: ${LINKEDIN_CLIENT_SECRET:""}

springdoc:
  api-docs:
    path: /v3/api-docs # OpenAPI JSON path (default)
  swagger-ui:
    path: /docs # UI entry path (redirects to /swagger-ui/index.html)
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha

# src/main/resources/application.yaml
cors:
  allowed-origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
    - "http://localhost:5173" # Vite React default port
    - "http://127.0.0.1:5173"

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO

azure:
  storage:
    connection-string: "${AZURE_STORAGE_CONNECTION_STRING:DefaultEndpointsProtocol=https;AccountName=headhunterstorage;AccountKey=J5wBrVeufVXHdxnrBWSIKSE8Q8SnJ4onHA+NZW58mXJWUvn/4TcljiAGeQQh2EE9qjZUWUql36GF+AStVmQeJA==;EndpointSuffix=core.windows.net}"
    container-name: ${AZURE_STORAGE_CONTAINER_NAME:uploads}
