spring:
  application:
    name: backend
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: "jdbc:mysql://localhost:3307/headhunt"
    username: root
    password: root
  mail:
    host: smtp.gmail.com
    port: 587
    username: datnh.work@gmail.com
    password: ttbl wjzq blsg ebar
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    from: noreply@headhunt.app

server:
  port: 8080
  servlet:
    context-path: /headhunt

jwt:
  signerKey: RikkeisoftHCMcity9998hIrNT3QZjFzSdzZ3YvFWhQyoV4HnOrMbcsrIKMgHMlV

springdoc:
  api-docs:
    path: /v3/api-docs # OpenAPI JSON path (default)
  swagger-ui:
    path: /docs # UI entry path (redirects to /swagger-ui/index.html)
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha

# src/main/resources/application.yaml
cors:
  allowed-origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
    - "http://localhost:5173" # Vite React default port
    - "http://127.0.0.1:5173"

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

azure:
  storage:
    connection-string: "DefaultEndpointsProtocol=https;AccountName=headhunterstorage;AccountKey=J5wBrVeufVXHdxnrBWSIKSE8Q8SnJ4onHA+NZW58mXJWUvn/4TcljiAGeQQh2EE9qjZUWUql36GF+AStVmQeJA==;EndpointSuffix=core.windows.net"
    container-name: "uploads"
